# Generated by Django 3.0 on 2020-02-03 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_title', models.CharField(max_length=100)),
                ('state_image', models.ImageField(upload_to='media/images')),
                ('state_slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'State',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_image', models.ImageField(upload_to='')),
                ('city_title', models.CharField(max_length=100)),
                ('city_about', models.TextField()),
                ('city_slug', models.SlugField(max_length=100, unique=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.State')),
            ],
        ),
    ]
